<?php

class sfDynamicsConfigHandler extends sfYamlConfigHandler
{
  public function execute($configFiles)
  {
    // retrieve yaml data
    $config = $this->parseYamls($configFiles);

    $code = sprintf("<?php\n" .
                    "// auto-generated by %s\n" .
                    "// date: %s\n" .
                    "sfConfig::set('my_stupid_config_entry', %s);",
                    __CLASS__,
                    date('Y-m-d H:i:s'),
                    var_export($config, 1));

    return $code;
  }
}
